PACKAGE_NAME="kunlun-module-dkms"
PACKAGE_VERSION="4.33.0"
AUTOINSTALL="yes"
KUNLUN_CC=/usr/bin/gcc
KERNELDIR=$kernel_source_dir
KERNELOUT=
MAKE[0]="'make' -j2 IGNORE_XEN_PRESENCE=1 IGNORE_PREEMPT_RT_PRESENCE=1 IGNORE_CC_MISMATCH=1 CC=$KUNLUN_CC KERNELDIR=$KERNELDIR KERNELOUT=$KERNELOUT modules"

BUILT_MODULE_NAME[0]="kunlun"
DEST_MODULE_LOCATION[0]="/extra"
