KUNLUN_SOURCES ?=
KUNLUN_SOURCES_CXX ?=

KUNLUN_SOURCES += kunlun/kl_compat.c
KUNLUN_SOURCES += kunlun/kl_cxpu.c
KUNLUN_SOURCES += kunlun/kl_fops.c
KUNLUN_SOURCES += kunlun/kl_hcm.c
KUNLUN_SOURCES += kunlun/kl_main.c
KUNLUN_SOURCES += kunlun/kl_mm.c
KUNLUN_SOURCES += kunlun/kl_proc.c
KUNLUN_SOURCES += kunlun/kl_war.c

KUNLUN_SOURCES += kunlun/ctrldev/kl_ctrl.c

KUNLUN_SOURCES += kunlun/kl1/control_node.c
KUNLUN_SOURCES += kunlun/kl1/device.c
KUNLUN_SOURCES += kunlun/kl1/device_state.c
KUNLUN_SOURCES += kunlun/kl1/exception.c
KUNLUN_SOURCES += kunlun/kl1/xpu_dma.c
KUNLUN_SOURCES += kunlun/kl1/xpu_drv.c
KUNLUN_SOURCES += kunlun/kl1/xpu_fops.c
KUNLUN_SOURCES += kunlun/kl1/xpu_hbm.c
KUNLUN_SOURCES += kunlun/kl1/xpu_hw.c
KUNLUN_SOURCES += kunlun/kl1/xpu_intc.c
KUNLUN_SOURCES += kunlun/kl1/xpu_ioctl.c
KUNLUN_SOURCES += kunlun/kl1/xpu_irq.c
KUNLUN_SOURCES += kunlun/kl1/xpu_mem.c
KUNLUN_SOURCES += kunlun/kl1/xpu_monitor.c
KUNLUN_SOURCES += kunlun/kl1/xpu_pd.c
KUNLUN_SOURCES += kunlun/kl1/xpu_proc.c
KUNLUN_SOURCES += kunlun/kl1/xpu_sched.c
KUNLUN_SOURCES += kunlun/kl1/xpu_session.c
KUNLUN_SOURCES += kunlun/kl1/xpu_sse.c
KUNLUN_SOURCES += kunlun/kl1/xpu_tq.c

KUNLUN_SOURCES += kunlun/kl2/control_node.c
KUNLUN_SOURCES += kunlun/kl2/device_state.c
KUNLUN_SOURCES += kunlun/kl2/dma.c
KUNLUN_SOURCES += kunlun/kl2/dbgm.c
KUNLUN_SOURCES += kunlun/kl2/event.c
KUNLUN_SOURCES += kunlun/kl2/exception.c
KUNLUN_SOURCES += kunlun/kl2/fops.c
KUNLUN_SOURCES += kunlun/kl2/gddr_config.c
KUNLUN_SOURCES += kunlun/kl2/hw.c
KUNLUN_SOURCES += kunlun/kl2/hwq.c
KUNLUN_SOURCES += kunlun/kl2/img_proc.c
KUNLUN_SOURCES += kunlun/kl2/intc.c
KUNLUN_SOURCES += kunlun/kl2/ioctl.c
KUNLUN_SOURCES += kunlun/kl2/irq.c
KUNLUN_SOURCES += kunlun/kl2/kl2_regs.c
KUNLUN_SOURCES += kunlun/kl2/main.c
KUNLUN_SOURCES += kunlun/kl2/mbox.c
KUNLUN_SOURCES += kunlun/kl2/p2p.c
KUNLUN_SOURCES += kunlun/kl2/proc.c
KUNLUN_SOURCES += kunlun/kl2/ram_blk.c
KUNLUN_SOURCES += kunlun/kl2/session.c
KUNLUN_SOURCES += kunlun/kl2/spec.c
KUNLUN_SOURCES += kunlun/kl2/sse.c
KUNLUN_SOURCES += kunlun/kl2/util.c
KUNLUN_SOURCES += kunlun/kl2/video.c
KUNLUN_SOURCES += kunlun/kl2/video_cache.c
KUNLUN_SOURCES += kunlun/kl2/video_dec.c
KUNLUN_SOURCES += kunlun/kl2/video_enc.c
KUNLUN_SOURCES += kunlun/kl2/video_perf.c

KUNLUN_SOURCES += kunlun/port/nv.c
KUNLUN_SOURCES += kunlun/port/nv-caps.c
KUNLUN_SOURCES += kunlun/port/nv-dma.c
KUNLUN_SOURCES += kunlun/port/nv-kthread-q.c
KUNLUN_SOURCES += kunlun/port/nv-procfs.c
KUNLUN_SOURCES += kunlun/port/nv-procfs-utils.c
KUNLUN_SOURCES += kunlun/port/os-interface.c
KUNLUN_SOURCES += kunlun/port/os-mlock.c
KUNLUN_SOURCES += kunlun/port/os-pci.c
KUNLUN_SOURCES += kunlun/port/os-registry.c
KUNLUN_SOURCES += kunlun/port/os-usermap.c
