#ifndef BAIDU_XPU_API_INCLUDE_XPU_REFACTOR_CONTEXT_LAUNCH_CFG_H
#define BAIDU_XPU_API_INCLUDE_XPU_REFACTOR_CONTEXT_LAUNCH_CFG_H

#define FIXED_CLUSTER_NUM(num) num
#define FIXED_SDNN_NUM(num) num

#endif